//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharePointDemo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharePointDemo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharePointDemo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharePointDemo.Resources.SharePointDemo", typeof(SharePointDemo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the text of the &apos;Read More&apos; link.
        /// </summary>
        internal static string ReadMoreText_Description {
            get {
                return ResourceManager.GetString("ReadMoreText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Read More&apos; link text.
        /// </summary>
        internal static string ReadMoreText_Name {
            get {
                return ResourceManager.GetString("ReadMoreText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the url of the &apos;Read More&apos; link.
        /// </summary>
        internal static string ReadMoreUrl_Description {
            get {
                return ResourceManager.GetString("ReadMoreUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Read More&apos; link url.
        /// </summary>
        internal static string ReadMoreUrl_Name {
            get {
                return ResourceManager.GetString("ReadMoreUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the text of the &apos;See More&apos; link.
        /// </summary>
        internal static string SeeMoreText_Description {
            get {
                return ResourceManager.GetString("SeeMoreText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;See More&apos; link text.
        /// </summary>
        internal static string SeeMoreText_Name {
            get {
                return ResourceManager.GetString("SeeMoreText_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the url of the &apos;See More&apos; link.
        /// </summary>
        internal static string SeeMoreUrl_Description {
            get {
                return ResourceManager.GetString("SeeMoreUrl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;See More&apos; link url.
        /// </summary>
        internal static string SeeMoreUrl_Name {
            get {
                return ResourceManager.GetString("SeeMoreUrl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo.
        /// </summary>
        internal static string WebPart_Category {
            get {
                return ResourceManager.GetString("WebPart_Category", resourceCulture);
            }
        }
    }
}
